# Generated by Django 2.1.3 on 2018-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='how_much_favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.IntegerField(default=0),
        ),
    ]
