# Generated by Django 2.1.3 on 2018-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addAuthBook', '0002_book_bookcover'),
        ('userProfil', '0002_auto_20181112_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoriteBooks',
            field=models.ManyToManyField(to='addAuthBook.Book'),
        ),
    ]
