# Generated by Django 2.1.3 on 2018-11-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfil', '0003_profile_favoritebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
    ]
