# Generated by Django 2.1.3 on 2018-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfil', '0004_remove_profile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favoriteBooks',
            field=models.ManyToManyField(blank=True, null=True, to='addAuthBook.Book'),
        ),
    ]
